### PR TITLE
Style

### PR DESCRIPTION
**Pull request by johnellison**
+ Add initial landing page
+ Style gameboard, game/show
+ Add Dashboard
+ Move My Games into My Dashboard

### CODE REVIEW

**Comment by kenmazaika** [comment]
This looks amazing, John!

**Comment by kenmazaika** [comment]
What do you think about featuring a few of the more complicated pieces of code that you guys worked on, on the landing page?  If you're looking to showcase this as part of a coding portfolio it would be even more impressive if you linked to complex pull requests like:

* Getting Check Functionality Working
* Hooking up Piece Capture Logic
* Diagonal Move Functionality

**Comment by washburnad** [comment]
Applause

**Comment by johnellison** [comment]
That's a great thought. We should totally include some code samples as you mentioned. How would you envision the layout of linking to pull requests?

**Comment by kenmazaika** [comment]
I'm not 100% sure.  Here's a poorly designed page I made to highlight the specific commits I've made to different open source projects.  It doesn't look awesome, but you can see how I did it.

http://kenmazaika.github.io/opensource.html

You have some space on the homepage here.  http://take.ms/FLu50

Just some thoughts.

**Pull request merged**
